### ISSUE TITLE
Make discord and hugging face front page icons responsive

### ISSUE THREAD

**Issue by apkatsikas** [speechbrain/speechbrain.github.io#19]
They end up disappearing on vertical mobile resolutions.
![image](https://user-images.githubusercontent.com/24813300/234906526-361fd735-d8c2-4b84-a337-01b783a896c8.png)

**Comment by apkatsikas** [comment]
@Adel-Moumen  - due to this line, the hugging face will always be hidden in mobile views - https://github.com/speechbrain/speechbrain.github.io/blob/2effefa39adf5c86070f0dfbe4e20e708eaf9842/css/responsive.css#L117

I can fix for the Discord link, but I can't fix for the hugging face without modifying the CSS there - and it would seem to be expected/desired behavior based on that link.

**Comment by Adel-Moumen** [comment]
Weird. I don't think this is a desired behaviour tbh...

**Comment by apkatsikas** [comment]
@Adel-Moumen fix here - https://github.com/speechbrain/speechbrain.github.io/pull/20

**Comment by Adel-Moumen** [comment]
Fixed in #20 :)
