### ISSUE TITLE
difference in conformer model train using speechbrain version-0.5.11 and version-0.5.14

### ISSUE THREAD

**Issue by gupnaval** [speechbrain/speechbrain.github.io#21]
I used speechbrain in a docker environment for version 0.5.11 with pytorch-1.11 and CUDA 11.1 which was working fine.

When I tried using the same docker image of speechbrain  in CUDA-11.9, there was issue in using the GPUs, so I created a new docker image which supported CUDA-11.9, however in this I have to reinstall speechbrain for version 1.13 which was supported on torch-1.13 for CUDA11.8.

In this docker image which was working fine, I used the same training script (which I used in speechbrain version-0.5.11) and it was working fine and all the hyperparameters in train.yaml were also unchanged. However the model which was created was created, was not the same model as I got in speechbrain-0.5.11. I tried to debug this, but could not conclude anything particular, like whether it is due to speechbrain version change or pytorch version change or if there is a change in architecture of speechbrain internally.

I am attaching the error snapshot of the difference in models from two different speechbrain versions.

_**RuntimeError: Error(s) in loading state_dict for ModuleDict:
	Missing key(s) in state_dict: "0.convblock_0.convs.norm_0.norm.running_mean", "0.convblock_0.convs.norm_0.norm.running_var", "0.convblock_1.convs.norm_0.norm.running_mean", "0.convblock_1.convs.norm_0.norm.running_var", "1.encoder.layers.0.convolution_module.after_conv.0.running_mean", "1.encoder.layers.0.convolution_module.after_conv.0.running_var", "1.encoder.layers.1.convolution_module.after_conv.0.running_mean", "1.encoder.layers.1.convolution_module.after_conv.0.running_var", "1.encoder.layers.2.convolution_module.after_conv.0.running_mean", "1.encoder.layers.2.convolution_module.after_conv.0.running_var", "1.encoder.layers.3.convolution_module.after_conv.0.running_mean", "1.encoder.layers.3.convolution_module.after_conv.0.running_var", "1.encoder.layers.4.convolution_module.after_conv.0.running_mean", "1.encoder.layers.4.convolution_module.after_conv.0.running_var", "1.encoder.layers.5.convolution_module.after_conv.0.running_mean", "1.encoder.layers.5.convolution_module.after_conv.0.running_var", "1.encoder.layers.6.convolution_module.after_conv.0.running_mean", "1.encoder.layers.6.convolution_module.after_conv.0.running_var", "1.encoder.layers.7.convolution_module.after_conv.0.running_mean", "1.encoder.layers.7.convolution_module.after_conv.0.running_var", "1.encoder.layers.8.convolution_module.after_conv.0.running_mean", "1.encoder.layers.8.convolution_module.after_conv.0.running_var", "1.encoder.layers.9.convolution_module.after_conv.0.running_mean", "1.encoder.layers.9.convolution_module.after_conv.0.running_var", "1.encoder.layers.10.convolution_module.after_conv.0.running_mean", "1.encoder.layers.10.convolution_module.after_conv.0.running_var", "1.encoder.layers.11.convolution_module.after_conv.0.running_mean", "1.encoder.layers.11.convolution_module.after_conv.0.running_var". 
	size mismatch for 0.convblock_0.convs.norm_0.norm.weight: copying a param with shape torch.Size([40, 64]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for 0.convblock_0.convs.norm_0.norm.bias: copying a param with shape torch.Size([40, 64]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for 0.convblock_1.convs.norm_0.norm.weight: copying a param with shape torch.Size([20, 32]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for 0.convblock_1.convs.norm_0.norm.bias: copying a param with shape torch.Size([20, 32]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for 1.encoder.layers.0.convolution_module.after_conv.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).
	size mismatch for 1.encoder.layers.1.convolution_module.after_conv.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).
	size mismatch for 1.encoder.layers.2.convolution_module.after_conv.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).
	size mismatch for 1.encoder.layers.3.convolution_module.after_conv.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).
	size mismatch for 1.encoder.layers.4.convolution_module.after_conv.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).
	size mismatch for 1.encoder.layers.5.convolution_module.after_conv.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).
	size mismatch for 1.encoder.layers.6.convolution_module.after_conv.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).
	size mismatch for 1.encoder.layers.7.convolution_module.after_conv.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).
	size mismatch for 1.encoder.layers.8.convolution_module.after_conv.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).
	size mismatch for 1.encoder.layers.9.convolution_module.after_conv.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).
	size mismatch for 1.encoder.layers.10.convolution_module.after_conv.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).
	size mismatch for 1.encoder.layers.11.convolution_module.after_conv.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).**_

Please provide guidance and help in this regard.

Naval

**Comment by TParcollet** [comment]
Hi, yes the yaml changed since this version. This is because the new architecture reaches 2.0 of wer on test clean. The model is better.

**Comment by gupnaval** [comment]
Thanks TParcolett,
For the reply, but I used same set of parameters and also the same script for training the model but still the models derived out of two speechbrain versions (0.5.11 and 0.5.14) are different.

So now how shall I solve the issue I am facing. The error output shown above is the model mismatches from 2 different models, while doing onnx conversion.

**Comment by TParcollet** [comment]
Alright, can we have a look at the yaml and training script?

**Comment by gupnaval** [comment]
[train_file_and_config_used_for_training.zip](https://github.com/speechbrain/speechbrain.github.io/files/12450561/train_file_and_config_used_for_training.zip)

Hi TParcolett,

Sorry for delay, I am attaching train.py and conformer.yaml files used for training.

**Comment by Adel-Moumen** [comment]
Please continue the discussion here: https://github.com/speechbrain/speechbrain/issues/2141

Thanks.
