### ISSUE TITLE
Question about releases schedule

### ISSUE THREAD

**Issue by msh9184** [speechbrain/speechbrain.github.io#6]
When will it be released? I am really waiting..!

**Comment by jgbradley1** [comment]
I am also interested in this. Has covid-19 pushed the release schedule back?

**Comment by StuartIanNaylor** [comment]
Yeah its nearly 2021 and not much to show?

**Comment by mravanelli** [comment]
We are working hard on that. The code and the baselines are almost ready.
We need to complete the documentation, tutorials, and beta testing phase.
We confirm SpeechBrain will be released in early winter but we still don't
have an official release date.
